### ISSUE TITLE
对18comic内地镜像站的支持

### ISSUE THREAD

**Issue by Carolove7** [MapoMagpie/eh-view-enhance#102]
**Describe the bug**
目前通过GPT自行修改图中部分代码实现了对 https://jmcomicgo.org/ 中内地分流的支持，希望作者大大更新类似功能。其中 @match 貌似不支持域名部分的通配符 ，所以根据提示使用了 @include 来匹配(**P1**)，发现依旧没有弹出按钮于是对正则进行了修改(**P2**)。
**Browser And Version**
Cent Browser 版本 5.1.1130.129（64 位） (Chromium 118.0.5993.159)
**Log**
无
**Screenshots**
![QQ20240930-200112](https://github.com/user-attachments/assets/73695562-7f97-46d0-90b7-1a57030ece43)
![QQ20240930-195944](https://github.com/user-attachments/assets/176c13ec-1963-41e6-ae24-513218025e07)

**Comment by MapoMagpie** [comment]
其实可以直接修改@match为`*://*/*` 匹配所有的网站，然后在某个已经生效的站点中打开脚本进行生效规则的配置。
配置 > 站点配置 > 添加生效规则输入 `镜像站地址\/album\/(\d+)`

我没有将@match指定为匹配所有网站是因为这样修改后，Greasyfork无法再通过站点搜索到这个脚本了。

**Comment by uaaazcc** [comment]
> 其实可以直接修改@match为`*://*/*` 匹配所有的网站，然后在某个已经生效的站点中打开脚本进行生效规则的配置。 配置 > 站点配置 > 添加生效规则输入 `镜像站地址\/album\/(\d+)`
> 
> 我没有将@match指定为匹配所有网站是因为这样修改后，Greasyfork无法再通过站点搜索到这个脚本了。

@MapoMagpie 大佬，为啥我添加镜像站后无法确定，点左上角那个对号好像没用，还是生效不了

**Comment by uaaazcc** [comment]
> 其实可以直接修改@match为`*://*/*` 匹配所有的网站，然后在某个已经生效的站点中打开脚本进行生效规则的配置。 配置 > 站点配置 > 添加生效规则输入 `镜像站地址\/album\/(\d+)`
> 
> 我没有将@match指定为匹配所有网站是因为这样修改后，Greasyfork无法再通过站点搜索到这个脚本了。

@MapoMagpie 大佬，为什么我添加镜像站后仍然没有出现图标呢？我规则输入的是：18comic-16promax.club\/album\/(\d+)

**Comment by uaaazcc** [comment]
> 其实可以直接修改@match为`*://*/*` 匹配所有的网站，然后在某个已经生效的站点中打开脚本进行生效规则的配置。 配置 > 站点配置 > 添加生效规则输入 `镜像站地址\/album\/(\d+)`
> 
> 我没有将@match指定为匹配所有网站是因为这样修改后，Greasyfork无法再通过站点搜索到这个脚本了。

@MapoMagpie 大佬，我添加镜像站网站后仍然没有图标，我规则输入的是：18comic-16promax.club\/album\/(\d+)

**Comment by uaaazcc** [comment]
> 其实可以直接修改@match为`*://*/*` 匹配所有的网站，然后在某个已经生效的站点中打开脚本进行生效规则的配置。 配置 > 站点配置 > 添加生效规则输入 `镜像站地址\/album\/(\d+)`
> 
> 我没有将@match指定为匹配所有网站是因为这样修改后，Greasyfork无法再通过站点搜索到这个脚本了。
 大佬，我添加镜像站后仍然没有生效啊，添加的规则是`18comic-16promax.club\/album\/(\d+)`

**Comment by HibernalGlow** [comment]
wn01.uk也匹配不到

**Comment by HibernalGlow** [comment]
return /(wnacg.com|wn\d{2}.cc|wn\d{2}.uk)\/photos-index/; 改了这行能用

**Comment by Carolove7** [comment]
> return /(wnacg.com|wn\d{2}.cc|wn\d{2}.uk)/photos-index/; 改了这行能用

👌新版本对jm的支持很好了
