### ISSUE TITLE
显示绿色下载完了，但是大图打开全看不了，有些就能看，有些就是这样

### ISSUE THREAD

**Issue by rainboat17** [MapoMagpie/eh-view-enhance#105]
**Describe the bug**
在此处描述问题

**Browser And Version**
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？

**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

**Screenshots**
如果可以，请提供安全的图片
![123](https://github.com/user-attachments/assets/bffe0a25-9783-4766-9097-cc0dd8819505)

**Comment by rainboat17** [comment]
1.29版本的谷歌浏览器

**Comment by rainboat17** [comment]
https://exhentai.org/g/2535072/34b55a4aa5/
今天进去还是这样，我看有些画廊是这样，但是大部分都是正常的，不知道为啥。。。多谢解答

**Comment by MapoMagpie** [comment]
network.hath(e-hentai的图片服务器)返回的不是图片，而是HTML页面，你可以继续点击下载，将下载后的图片用文本编辑器打开，应该就能看到具体是什么内容了。

有几种可能：
杀毒软件，卡巴斯基会拦截e-hentai的内容分发服务`network.hath`，而且只拦截浏览器拓展对`network.hath`的请求。
https://github.com/MapoMagpie/eh-view-enhance/issues/76#issuecomment-2256259350

其他代理类的浏览器拓展影响了，使得返回的内容变成了文本。
https://github.com/MapoMagpie/eh-view-enhance/issues/72#issuecomment-2231430367

或者是SSL证书什么的
https://github.com/MapoMagpie/eh-view-enhance/issues/97#issuecomment-2361473971

**Comment by rainboat17** [comment]
好的好的谢谢，我自己去研究研究看看
