### ISSUE TITLE
按方向鍵的左右或a和d會退出

### ISSUE THREAD

**Issue by Drestone** [MapoMagpie/eh-view-enhance#107]
**Describe the bug**
在此处描述问题
在exhentai中按方向鍵的左右或a和d會退出，會變成跳去網站的下一頁而不是下一張圖片
**Browser And Version**
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？
edge
**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

**Screenshots**
如果可以，请提供安全的图片

**Comment by MapoMagpie** [comment]
在Edge上没有复现，而且原本页面上按A和D也没有对应的操作，不会去网站的下一页或上一页。只有原本的阅读页面A和D才有用，但是脚本只生效在画廊详情界面，所以正常来说A和D都不会影响脚本。

检查一下你有装什么其他的脚本吗，或者浏览器拓展，为exhentai的画廊页添加了A和D的事件。
