### ISSUE TITLE
Feature request - Adjustable background color and opacity

### ISSUE THREAD

**Issue by lnp5131** [MapoMagpie/eh-view-enhance#108]
Allow adjusting background-color found in .big-img-frame on lines 7921-7931

```
.big-img-frame {
  position: fixed;
  width: 100%;
  height: 100%;
  top: 0;
  right: 0;
  overflow: auto;
  scrollbar-width: none;
  z-index: 2001;
  background-color: #000000d6;
}
```

**Comment by MapoMagpie** [comment]
You can change the custom property `--ehvp-big-images-bg` in `.ehvp-root {}`，
Actually, you can override any style in the `Style Configuration`.
