### ISSUE TITLE
Bug: "Error: warn: failed query image nodes!" on exhentai

### ISSUE THREAD

**Issue by Pamlau** [MapoMagpie/eh-view-enhance#109]
**Describe the bug**
Whenever I try to use the gallery viewer on https://exhentai.org it shows up that error, this issue started happening 1-2 days ago or so. I also tried disabling every other script/extension even though that might not be the problem considering it works on any other website like pixiv and the normal e-hentai gallery

**Browser And Version**
Opera GX LVL 6 (core: 114.0.5282.123)

**Log**
![image](https://github.com/user-attachments/assets/df879fb5-2680-4a26-8ece-26177619bc9d)

**Screenshots**

![image](https://github.com/user-attachments/assets/b531328e-d421-4a48-a062-b5900c4e95bc)

**Comment by MapoMagpie** [comment]
update to 4.9.3, I have fixed this issue today.
