### ISSUE TITLE
Exhentai: failed query image nodes | 加載圖片失敗

### ISSUE THREAD

**Issue by Drestone** [MapoMagpie/eh-view-enhance#111]
**Describe the bug**
在此处描述问题
Exhentai使用插件加載圖片失敗，但E-hentai卻可以正常加載。不用插件直接點開圖片是可以圖片正常加載出來的

**Browser And Version**
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？
Edge

**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。
[exhentai.org-1729919079746.log](https://github.com/user-attachments/files/17529082/exhentai.org-1729919079746.log)

**Screenshots**
如果可以，请提供安全的图片
![image](https://github.com/user-attachments/assets/fa9c452e-ee9d-4efd-8a65-fd6ebd14f3fe)

**Comment by MapoMagpie** [comment]
update to 4.9.4
更新到4.9.4
8e79ceb48b5adb3a8faded5d350b6425febabced
