### ISSUE TITLE
Plugin is broken on https://hitomi.la

### ISSUE THREAD

**Issue by mordemand** [MapoMagpie/eh-view-enhance#116]
**Describe the bug**
在此处描述问题
The plugin is broken on https://hitomi.la starting from today I think.

**Browser And Version**
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？
Firefox 132.0.2 (64-bit)

**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。
attached console log: [console-export-2024-11-27_0-23-51.txt](https://github.com/user-attachments/files/17923341/console-export-2024-11-27_0-23-51.txt)

**Screenshots**
如果可以，请提供安全的图片
Cannot add a full screen screenshot because nsfw, but fortunately 1 page is safe to screenshot:
![image](https://github.com/user-attachments/assets/f3781068-542f-4e19-8d05-2c137c8b08e4)

**Comment by MapoMagpie** [comment]
![grim_20241127_102523](https://github.com/user-attachments/assets/87f37c70-b3fa-4d53-bb9e-3491b7185729)
Tampermonkey > Dashboard > Edit Comic Looms (click) > Settings > XHR Security > clear `User Domain Blacklist`.

Next time you visit hitomi.la, Tampermonkey will pop up a confirmation tab, select `Always allow domain` or `Always allow all domains`.
I recently removed the `@connect  some.adult.site` in the script and used `@connect *` instead.

**Comment by mordemand** [comment]
Oh, not sure why hitomi domain got blacklisted, maybe I misclick in the pop up?
![image](https://github.com/user-attachments/assets/85e3078b-1b3b-46f3-8c1e-a78ce23133e5)

I just need to remove the blacklist and now it's working again. Thank you for your help.
