### ISSUE TITLE
需要单页画面自动缩放布满屏幕

### ISSUE THREAD

**Issue by Aurora-A-F** [MapoMagpie/eh-view-enhance#118]
4.10.0版本，使用PAGE模式浏览，每屏1页时。

当图片宽度大于浏览器窗口宽度时（竖屏时大部分的图都比窗口宽），插件会将图片的高度缩放到窗口高度，导致图片超出屏幕宽度，需要滚动到最右才会翻页。希望增加自选图片缩放方式的选项（比如 横向铺满、纵向铺满、完整显示）。

我用旧版本时就是图片完整显示，细长竖图和宽图都缩放到一屏，自动升级上来到4.10后变成纵向缩放了，而且没有找到相应的设置选项，缩放也不能调节到小于100%。彻底删除插件重装也一样。

连续滚轴模式不能替代，因为无法实现鼠标滚轮滚一下翻一整页。

**Comment by MapoMagpie** [comment]
已更新，只有在单页阅读、并且没有进行缩放时，也就是最常用的阅读模式时，图片会自适应屏幕宽度。
