### ISSUE TITLE
自動加載好像沒有用

### ISSUE THREAD

**Issue by Drestone** [MapoMagpie/eh-view-enhance#120]
**Describe the bug**
在此处描述问题
開啟自動加載後，要手動下滑，圖片才會加載，而且任何網站都是一樣

**Browser And Version**
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？
edge

**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

**Screenshots**
如果可以，请提供安全的图片

**Comment by MapoMagpie** [comment]
无法复现此问题。请检查配置是否确定开启了`自动加载`。或者`打开浏览器控制台，导出或复制控制台日志，粘贴到此处。`

或者在脚本管理器中点击此脚本，点击Storage或Values标签，删除其中的内容后添加空的花括号`{}`以重置配置。
