### ISSUE TITLE
鼠标右键＋滚轮无法放大

### ISSUE THREAD

**Issue by lklen** [MapoMagpie/eh-view-enhance#14]
为什么我鼠标右键＋滚轮无法放大啊
在此处描述问题

谷歌浏览器
![屏幕截图 2022-07-25 205425](https://user-images.githubusercontent.com/83005595/180782189-5e28fcc0-df1c-46bf-aa4c-8c68bc94918f.png)
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？

**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

**Screenshots**
如果可以，请提供安全的图片

**Comment by lklen** [comment]
![Uploading 屏幕截图 2022-07-25 205549.png…]()

**Comment by lklen** [comment]
![屏幕截图 2022-07-25 205549](https://user-images.githubusercontent.com/83005595/180782659-eb24146d-c8ff-4073-b746-21e8e37d83ba.png)

**Comment by kamo2020** [comment]
放大图片只能放大到图片宽度占满浏览器的宽度为止。
之后会调整下图片的放大机制
