### ISSUE TITLE
scrolling problem

### ISSUE THREAD

**Issue by Owyn** [MapoMagpie/eh-view-enhance#18]
**Describe the bug**
After I turn on the script and go to activate its mode for the gallery - I can no longer use keyboard (arrows and SPACE) to scroll, only the mouse wheel) - that's rather inconvinient

**Browser And Version**
Firefox 109

**Comment by MapoMagpie** [comment]
[improve keyboard control](https://github.com/MapoMagpie/eh-view-enhance/commit/edd397a55c4d3b16882c6c8b711f402b76956712)
check the help page > Keyboard, Now there are different keyboard control methods.
