### ISSUE TITLE
压缩包中图片名的冒号会引起bug

### ISSUE THREAD

**Issue by dudulu23** [MapoMagpie/eh-view-enhance#20]
**Describe the bug**
图片名有冒号会让压缩软件无法直接打开图片，那些能直接识别压缩包漫画管理软件也会因为冒号无法识别这个压缩包

**Comment by MapoMagpie** [comment]
[fix: downloaded file include :](https://github.com/MapoMagpie/eh-view-enhance/commit/f103ba07f7f0e7617aca27f2cde226db8de7e2e5)
