### ISSUE TITLE
那个移动鼠标翻页的新功能好像没用诶

### ISSUE THREAD

**Issue by FaraamQAQ** [MapoMagpie/eh-view-enhance#21]
**Describe the bug**
在此处描述问题

**Browser And Version**
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？

**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

**Screenshots**
如果可以，请提供安全的图片

**Comment by MapoMagpie** [comment]
咦？这个功能我一小时前才提交的，还没有发布到Greasyfork上，你是怎么知道的。
如果要用的话可以通过这个地址安装：https://github.com/MapoMagpie/eh-view-enhance/raw/master/dist/eh-view-enhance.user.js
只有在单页模式 + 放大图片时才有效。因为是刚加的，可能有什么体验上的问题，欢迎反馈。

**Comment by FaraamQAQ** [comment]
我更新了一下就有了hh
好像只能往后翻页？reverse选项不生效
看图的时候碰到比例比之前小的图会卡住，这个需要优化一下

ps：感觉不是很实用但还是辛苦作者了，自动翻页个人认为还是使用键盘控制会好一些，例如按1向左翻按2向右，添加暂停开始按钮，并且能自由设定翻页时间这样会好一些

**Comment by FaraamQAQ** [comment]
我更新一下有了hh
好像只能往后翻页？而且reverse选项不生效
看图的时候碰到比之前大的图会卡住，比较影响观看体验，这个需要优化一下

ps：感觉不是很实用但是还是辛苦作者了，自动翻页个人认为还是使用键盘控制会好一些，比如按1向左翻按2向右，添加暂停开始按钮，并且可以自由设定翻页时间这样会好一些

**Comment by FaraamQAQ** [comment]
我更新一下就有了hh
好像只能往后翻页？而且reverse选项不生效
看图的时候碰到比之前大的图会卡住，比较影响观看体验，这个需要优化一下

ps：感觉不是很实用翻页但是还是辛苦作者了，自动翻页个人认为还是使用键盘控制会好一些，比如增加调整方向快捷键，添加暂停开始按钮，并且可以自由设定翻页时间这样会好一些

**Comment by FaraamQAQ** [comment]
我更新一下就有了hh
好像只能往后翻页？而且reverse选项不生效
看图的时候碰到比之前小的图会卡住，比较影响观看体验，这个需要优化一下

ps：感觉不是很实用翻页但是还是辛苦作者了，自动翻页个人认为还是使用键盘控制会好一些，比如增加调整方向快捷键，添加暂停开始按钮，并且可以自由设定翻页时间这样会好一些

**Comment by FaraamQAQ** [comment]
还有就是那个超时时间是什么功能？

**Comment by MapoMagpie** [comment]
超时时间是加载大图的时间。
自动翻页的功能这个月底左右我会加上。鼠标移动翻页我再优化优化。

**Comment by FaraamQAQ** [comment]
嗯嗯，楼上老哥的问题我也注意到了，现在单页看图确实不能自适应缩放了

期待大大更新❤

**Comment by MapoMagpie** [comment]
> 以前可以自动自适应浏览器窗口缩放图片，现在的缩放默认100%太大了，能出一个默认自适应大小的功能吗

单页模式下，如果缩放过了图片那就只能保持这个宽度，点击RESET则和以前一样自动适应窗口高度。
连续阅读模式下，RESET默认所有图片80%的宽度，没法自适应高度。
也许我理解有误，可以详细描述下问题。

**Comment by SasamiyaNatsuki** [comment]
![H1W~F GG3E7YUS1V9NSLZYJ](https://github.com/MapoMagpie/eh-view-enhance/assets/79438105/f2459e6f-265c-488f-a5a2-be65e4fe4037)
昨天用把左下角移到右下角，今天开就跑到左上角去了，重装和重置都没用，也不知是不是浏览器问题，只能点开

**Comment by MapoMagpie** [comment]
> ![H1W~F GG3E7YUS1V9NSLZYJ](https://private-user-images.githubusercontent.com/79438105/286898823-f2459e6f-265c-488f-a5a2-be65e4fe4037.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTU1OTUsIm5iZiI6MTcwMTQxNTI5NSwicGF0aCI6Ii83OTQzODEwNS8yODY4OTg4MjMtZjI0NTllNmYtMjY1Yy00ODhmLWE1YTItYmU2NWU0ZmU0MDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA3MjEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlN2EwMDIyMmJmYWNmMDUwMjQ4Njg2ZTE2Y2VkYzllMmRmNTYyYjRjZTNiMjgzMGY4MTQ3NWNkMmM5YzMwYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3IMKYIKY4wkFJhW6Geq8JhK4RR3tt4MiLlvUrRxMUf4) 昨天用把左下角移到右下角，今天开就跑到左上角去了，重装和重置都没用，也不知是不是浏览器问题，只能点开

9965fdab570f3b05607ef875488c484cf3e72614
