### ISSUE TITLE
工具栏无法通过ESC收起

### ISSUE THREAD

**Issue by RJSackville** [MapoMagpie/eh-view-enhance#23]
画廊里面点击左下角图标进入缩略图查看模式之后 ，再按ESC键会返回到画廊，但是脚本的工具栏没有自动收起，还是在展开状态。

**Comment by MapoMagpie** [comment]
0180d664b3681e48b0b4a92338f05dd9cd15a713
修复了此问题，你可以通过这个地址直接安装修复后的版本，https://github.com/MapoMagpie/eh-view-enhance/raw/master/dist/eh-view-enhance.user.js
也可以等一周后从greasyfork更新。
