### ISSUE TITLE
关于 npm run build 的问题

### ISSUE THREAD

**Issue by kakuri2020** [MapoMagpie/eh-view-enhance#25]
我使用 npm install && npm run dev 之后，安装的 server:xxx 脚本是可以使用的

但是用 npm run build 生成的 dist 打包脚本，和你master上的目前有很大的差异（主要在一些以来顺序上），并且有一些错误没办法加载

[eh-view-enhance.user.zip](https://github.com/MapoMagpie/eh-view-enhance/files/13840592/eh-view-enhance.user.zip)

我想问一下你的build环境是什么：
以下是我的：
node -v
v18.17.1

npm -v
10.2.5

其余就是按照 package.json 里安装的。。。不知道为什么打包的文件差异这么大，甚至出现错误

**Comment by MapoMagpie** [comment]
node v21.2.0 npm 10.2.3
你打包的我试了下，出现的错误和我 npm run dev 重新热部署时的错误一样，不知道哪里的问题。
你可以试试切换到最新的node再打包试试。

**Comment by MapoMagpie** [comment]
我用node v18.x试了，打包后的文件没问题。我的系统是linux。

**Comment by kakuri2020** [comment]
windows平台下的node最多只有 v20.4.0, 我切换过去还是不行

我去linux试了一下，发现同样的操作，结果就和你master上的一样了

可能是windows下的什么神秘问题 😄

**Comment by kakuri2020** [comment]
我试了一下，可能是vite 或者node 或者别的什么在处理module 循环依赖的时候，两个平台下的表现不一样导致的

左边是linux 右边是 windows，在windows下一旦出现循环引用，就会有 xx$1 这样的变量出现。。导致代码出问题。

![image](https://github.com/MapoMagpie/eh-view-enhance/assets/155665830/e8ef01d3-d4d5-4ee1-be71-457f6cc9c842)

![image](https://github.com/MapoMagpie/eh-view-enhance/assets/155665830/296a7160-bc23-4511-a27a-5c3b31585ee6)

![image](https://github.com/MapoMagpie/eh-view-enhance/assets/155665830/1c0aa3ee-3887-4845-9544-1dbc58edbe3c)

![image](https://github.com/MapoMagpie/eh-view-enhance/assets/155665830/1808ceda-c4f3-41f2-bbde-a4aee0d6dd70)

**Comment by MapoMagpie** [comment]
还有这种事，真是涨见识了。我看看啥时候把循环依赖的问题处理了。
