### ISSUE TITLE
是不是把左右搞反了... 介绍里应该是左下角的阅读模式.

### ISSUE THREAD

**Issue by luminous030** [MapoMagpie/eh-view-enhance#27]

**Comment by MapoMagpie** [comment]
有一说一，确实。稍后会更新下说明文档。
你可以在这里安装新版本帮助我测试吗，优化了一些内存占用的问题，https://github.com/MapoMagpie/eh-view-enhance/raw/master/dist/eh-view-enhance.user.js

**Comment by MapoMagpie** [comment]
d23792c913156e545b1cbbe1627c621398fea96f
