### ISSUE TITLE
建议当画廊图片数量大于300时，才开启 unrender 列表

### ISSUE THREAD

**Issue by kakuri2020** [MapoMagpie/eh-view-enhance#28]
1. 如题，不然观感不太好，上下翻页要等一下才会出画面
这个unrender列表我觉得可能是为了节省内存搞的，对一般浏览而言，正常的画廊不太需要这个，所以建议搞个默认设置数量300以下不开启
2. 还有就是向上翻页时，如果上一行出现在窗口中，会强制向上滚动一段距离，感觉可以取消掉，不然画面会一直抖动（当然如果加了300的限制，这个应该就没什么影响了）

![image](https://github.com/MapoMagpie/eh-view-enhance/assets/11457297/3dedb39d-e4ca-4aac-be30-6a595c89d465)

3. 其次目前最新版本 4.1.16，控制台会报一些错误

![image](https://github.com/MapoMagpie/eh-view-enhance/assets/11457297/72c6559c-3ad2-48b5-9bce-765060c32545)

**Comment by MapoMagpie** [comment]
你用的什么浏览器，版本多少以及系统，我测试下。

**Comment by kakuri2020** [comment]
系统 Win10 22H2 19045.3930
浏览器 Chrome 版本 120.0.6099.217

**Comment by MapoMagpie** [comment]
修复了控制台报错的问题: c951f804787248dcaf72222049dae31e771234b5

> 还有就是向上翻页时，如果上一行出现在窗口中，会强制向上滚动一段距离，感觉可以取消掉，不然画面会一直抖动（当然如果加了300的限制，这个应该就没什么影响了）
这个问题是在什么情景下？阅读大图+连续阅读模式下，还是缩略图列表模式下？
是在阅读大图时，后面的缩略图列表会根据当前正在阅读的大图，自动滚动到对应的位置，然后自动滚动导致了画面抖动吗？

**Comment by kakuri2020** [comment]
> 修复了控制台报错的问题: [c951f80](https://github.com/MapoMagpie/eh-view-enhance/commit/c951f804787248dcaf72222049dae31e771234b5)
> 
> > 还有就是向上翻页时，如果上一行出现在窗口中，会强制向上滚动一段距离，感觉可以取消掉，不然画面会一直抖动（当然如果加了300的限制，这个应该就没什么影响了）
> 
> 这个问题是在什么情景下？阅读大图+连续阅读模式下，还是缩略图列表模式下？ 是在阅读大图时，后面的缩略图列表会根据当前正在阅读的大图，自动滚动到对应的位置，然后自动滚动导致了画面抖动吗？

缩略图列表模式下，我说的抖动不是说缩略图会上下移动，而是 你在缩略图模式下，向上缓慢翻的时候，每当上面出现新的一行，缩略图整体就会向上移动一小段距离

我期望的是在向上滚动的过程中，整个画面是连续的，不会出现瞬间的上移

**Comment by MapoMagpie** [comment]
我懂了，第二个问题是因为E站默认的小缩略图模式，这个模式是用精灵图切分成缩略图的，很模糊，就没支持这种模式，现在支持了，缩略图能获取到正常的图片了。
这样就不会在unrender时失去宽高信息，导致你说的现象。
6718dc6b96002b6c0e644b25b5ead1409af19800
