### ISSUE TITLE
自动加载会强制跳转到当前加载页

### ISSUE THREAD

**Issue by shibuyameltdown** [MapoMagpie/eh-view-enhance#29]
如题
检查了自动翻页是关闭的，就算拖回去他还会跳转
浏览器chrome，版本 120.0.6099.217。
tampermonkey版本5.0.1
部分log（不太懂）：
led to load resource: net::ERR_BLOCKED_BY_CLIENT
superdrag.js:134 [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.
(anonymous) @ superdrag.js:134
Show 1 more frame
Show less
adserver.juicyads.com/js/jads.js:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:35503 💉 脚本  不支持右键菜单
MenuProvider @ userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:35503
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:30384 💉 脚本  监听事件 update-database
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:30384 💉 脚本  监听事件 check-database
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:30384 💉 脚本  监听事件 get-tag
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:30384 💉 脚本  监听事件 get-tag-map
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:30384 💉 脚本  监听事件 get-tag-sha
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:34632 💉 脚本  获取 UI 翻译： /g/2774178/fa8067af0b/
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:35127 💉 脚本  有 664 个节点在注入前加载 Array(664)
init @ userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:35127
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:30384 💉 脚本  监听事件 tag-updated
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:30384 💉 脚本  监听事件 update-tag
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:36965 💉 脚本  标签数据库初始化完成
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:35212 💉 脚本  替换数据已经最新 530e3299bf6a0c20498a8c7e3baef7b741ee9848
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:35222 💉 脚本  获取替换数据: 207.7529296875 ms
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:30384 💉 脚本  监听事件 suggest-tag
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:32065 💉 脚本  标签提示
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:30723 💉 脚本  标签介绍
userscript.html?name=EhSyringe.user.js&id=b8e46af9-397d-425e-a951-a897d5098814:36122 💉 脚本  没有新版本
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:01:58 EHVP:空闲自加载启动:0
2userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:01:58 EHVP:要渲染的范围是:1-7
2userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:01:59 EHVP:要渲染的范围是:1-7
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:01:59 EHVP:第1张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:01:59 EHVP:要渲染的范围是:1-7
3userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:00 EHVP:要渲染的范围是:4-13
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:00 EHVP:空闲自加载启动:1
2userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:01 EHVP:要渲染的范围是:4-13
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:01 EHVP:要渲染的范围是:1-7
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:01 EHVP:第2张完成，大图所在第1张
3userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:02 EHVP:要渲染的范围是:1-7
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:03 EHVP:空闲自加载启动:2
2userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:03 EHVP:要渲染的范围是:1-7
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:04 EHVP:要渲染的范围是:1-7
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:04 EHVP:第3张完成，大图所在第1张
2userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:04 EHVP:要渲染的范围是:1-7
2userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:05 EHVP:要渲染的范围是:1-7
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:05 EHVP:空闲自加载启动:3
2userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:06 EHVP:要渲染的范围是:1-7
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:07 EHVP:第4张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:08 EHVP:要渲染的范围是:1-10
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:08 EHVP:空闲自加载启动:4
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:10 EHVP:第5张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:11 EHVP:要渲染的范围是:1-10
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:11 EHVP:空闲自加载启动:5
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:12 EHVP:第6张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:13 EHVP:空闲自加载启动:6
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:15 EHVP:第7张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:15 EHVP:空闲自加载启动:7
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:16 EHVP:要渲染的范围是:4-13
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:16 EHVP:第8张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:17 EHVP:空闲自加载启动:8
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:18 EHVP:第9张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:19 EHVP:空闲自加载启动:9
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:24 EHVP:第10张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:24 EHVP:空闲自加载启动:10
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:25 EHVP:要渲染的范围是:7-16
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:25 EHVP:第11张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:26 EHVP:空闲自加载启动:11
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:27 EHVP:第12张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:28 EHVP:空闲自加载启动:12
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:29 EHVP:第13张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:29 EHVP:空闲自加载启动:13
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:30 EHVP:要渲染的范围是:10-19
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:31 EHVP:第14张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:31 EHVP:空闲自加载启动:14
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:32 EHVP:第15张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:33 EHVP:空闲自加载启动:15
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:35 EHVP:第16张完成，大图所在第1张
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:36 EHVP:要渲染的范围是:13-22
userscript.html?name=E-HENTAI-VIEW-ENHANCE.user.js&id=077c534a-a10b-4b2e-a845-e7435fa7b068:140 2024/1/18 22:02:36 EHVP:空闲自加载启动:16

**Comment by MapoMagpie** [comment]
是不是进入缩略图列表界面后，还没有查看大图的情况下，你往下拉，然后过了一会自动滚动到第一行。

如果是这个现象的话，那就是因为第一张图片刚加载完，加载完就跳到第一行了，我会修复这个问题。

如果不是的话，还要麻烦你更详细地描述下现象。

**Comment by shibuyameltdown** [comment]
> 是不是进入缩略图列表界面后，还没有查看大图的情况下，你往下拉，然后过了一会自动滚动到第一行。
> 
> 如果是这个现象的话，那就是因为第一张图片刚加载完，加载完就跳到第一行了，我会修复这个问题。
> 
> 如果不是的话，还要麻烦你更详细地描述下现象。

好像不太一样，我录个屏试试

**Comment by shibuyameltdown** [comment]
https://mp4.ziyuan.wang/view.php/f55f6df3ab55fcc1c92a7bbe70cf774b.mp4
密码114514

**Comment by MapoMagpie** [comment]
没法复现视频里的现象，我检查了控制自动滚动的地方，加固了下可能存在的问题，如果还出现那大概率是灵异事件。
请更新下试试，要是还有这样的问题，检查下有没有什么和图片相关的脚本和拓展。

**Comment by shibuyameltdown** [comment]
更新之后解决了，感谢
