### ISSUE TITLE
望增加键盘和触屏操作的支持

### ISSUE THREAD

**Issue by URenko** [MapoMagpie/eh-view-enhance#3]
比如<kbd>↑</kbd><kbd>↓</kbd>翻页，<kbd>Esc</kbd>退出可能会更方便。
触屏上单指上滑可见页面滚动条滑动，但无法翻页，也许可以考虑hammer.js？
触屏也可以考虑类似[EhViewer](https://github.com/seven332/EhViewer)的操作方式

**Comment by kamo2020** [comment]
好，近期我会先把键盘操作加上，触屏要等下下下次更新

**Comment by MapoMagpie** [comment]
键盘与触屏操作已添加
