### ISSUE TITLE
Bug report：UI 自动收起、gallery 读取不全、下载不完整

### ISSUE THREAD

**Issue by inttimmy** [MapoMagpie/eh-view-enhance#31]
**浏览器版本：Edge 浏览器最新版本
网站：EH**

# Bug 1: 下载任务会干扰详情页收起

## 问题描述

使用 “下载” 界面 “开始下载” 启动自动下载和打包后，每自动开始一个新的下载任务时，都会导致已经展开的详情界面（如设置详情页、下载详情页）被**自动收起**。

正常情况下，似乎应是用户点击 bar 之外的部分时自动收起？

## 修复建议

增加关闭动画选项，或让这类详情界面不再被自动收回，需再点击一次对应按钮才能收起。

# Bug 2: 读取 gallery 不全

## 问题描述

有概率无法自动获取到完整数量的 gallery 图片。

虽然将插件宫格界面滚动到最下方，可以触发自动加载，但依然有概率无法加载完整数量的图像（**尤其是在点击悬浮窗，开启插件宫格界面前，已经在eh网页上处于 gallery 的非第一页时**）。

比如：一个 gallery 有 7 页，共 623 张 imgs，每页 100 张 imgs，如果在开启 gallery 前已经使用网页本身的页面跳转，跳至第 7 页（非第一页），那么插件就有可能无法获取到完整的 623 张 imgs，**只能获取 400、600 这样的 每页 imgs 数 的整数倍**。

由于此问题，将插件挂于后台自动下载时，可能无法获取到全部 imgs，导致下载不完整。

# Bug 3: 点击 “下载中...“ 按钮会导致下载不完整 + 无法自动打包

## 问题

只点击一次 “下载” 界面的 “开始下载”，能够正常下载。

当下载已经开始后，再次点击 “下载中...” 按钮时，可以观察到正在下载的数量增加了 $最大并行下载数$ 个，导致实际的并行下载数增加到 （点击 “下载中...” 时正在下载的数量 + $最大并行下载数$）个。不过这只是小问题（并行下载数临时超过设置限制），在这几个图片下载完成后，插件依然能够正常受到 $最大并行下载数$ 设置的限制。

以上不是最主要的问题，关键在于，如果用户点击了一次或多次 “下载中...” 按钮，会导致点击按钮时所下载的图片 index 附近，有的图片无法被正常下载和打包。最终，下载始终无法完成：当下载完成（imgs 总数 - $所设置的最大并行下载数$）个 imgs 后，下载就停滞了，按任何按钮都不能正常完成下载，只能通过 “强制下载已下载的图片” 来打包已下载的内容。

总结来说就是，**一旦手贱点击一次或多次 “下载中...” 按钮，gallery 中就会有 $最大并行下载数$ 个 imgs 无法被插件自动下载**。同时，由于在数量上看，还没有下载完，**插件也无法自动打包 zip**，只能手动强制打包。

## 修复建议

当按钮变为 “下载中......” 时禁止点击、触发回调

# 建议

- bar 上会显示正在查看的页数，但似乎没有输入页数跳页的功能。
- 希望 bar 可以在宫格界面进行折叠，喜欢使用宫格页浏览的人，会被长长的 bar 挡住一部分内容。
- 每次点击悬浮 bar，来关闭、开启扩展页面后，宫格页面的阅读进度都会被重置到顶部，希望能够记忆

我曾尝试克隆源码自行修复此问题，奈何自己 js 水平十分有限。如果需要，我可以尽可能向你提供更多 bug 信息。如果你能修复它们，我将肥肠感激！（为什么中文写出一股英文味）

**Comment by MapoMagpie** [comment]
好的，晚点我会看看什么情况，如果能提供画廊地址就更好了。

**Comment by MapoMagpie** [comment]
第二个问题我知道什么原因了，在画廊的最后一页时使用脚本就会出现，应该是分页元素的class被改变了。
第一个自动收起没复现，你说的`每自动开始一个新的下载任务时`是指每开始下载一张新的图片时，会被自动收起吗？
第三个问题暂时没复现，`下载中...`这个按钮是可以被多次点击的
总之我明天再测试测试。

**Comment by MapoMagpie** [comment]
阅读界面被再次展开后，不再重置到顶部: 1b1d5798a172936954a19e7aeaf7bad1e992a90d
修复页面读取不全: e54fbd7cb0bd2d14db0ebab3114271962d606cf8
修复输入页码跳页功能在Firefox不生效的问题: a5d91a23045e8bcf6fd9372d481d2f3f612dc657 
输入页码并跳页这个功能是有的，在缩略图网格页面，直接输入数字键，然后按回车就可以跳到对应的位置。只是输入时不显示。
如果没生效那就试试键盘上方那块横向的数字键区域，因为我没有带独立小键盘区域的键盘，测试不了。
当然我之后会考虑加上直接的输入元素。

剩下没解决的：
bar的折叠，后面会优化下，增加收起选项，收起后只剩下 `1/100` 这样的提示。
BUG3没复现，理论上只要图片加载了(边框变紫)，打包时就不会缺失。
BUG1没复现，我之后再研究研究，现在是，从设置详情页上移动回bar上会收回，我会先改改这里。

**Comment by MapoMagpie** [comment]
我换了三个浏览器分别在linux和windows下测试，没成功复现。
我注意到你似乎开了一种编辑模式，可以随意修改页面上的文字内容。
然后我手动将几个标签页也设置为可编辑模式，document.designMode = "on"，但还是没有复现。
试试禁用和编辑模式有关的脚本或拓展，再看看。

**Comment by MapoMagpie** [comment]
针对剩余的建议，我更新了下。你可以试试，有什么问题欢迎反馈。
