### ISSUE TITLE
[Feature] 允许仅为选中站点启用此脚本

### ISSUE THREAD

**Issue by Pil0tXia** [MapoMagpie/eh-view-enhance#33]
### 描述

eh-view-enhance 油猴脚本在多个网站上都是启用的，如 Pixiv 和 yande.re。但用户很有可能正在为 Pixiv 或 yande.re 使用另一个脚本，或不希望 eh-view-enhance 脚本在 Pixiv 和 yande.re 上启用。

例如，eh-view-enhance 脚本会在 yande.re 上使用搜索框并按下 Enter 时 错误地进入阅读模式。一旦用户此时从油猴插件禁用了此脚本，则此脚本在 ehentai 上也会被禁用。

直接修改 eh-view-enhance 脚本中的作用域可以临时解决此问题，给后续接收脚本更新带来了困难。

希望可以从脚本层面，配置脚本只在哪些站点上启用。

感谢！

**Comment by Pil0tXia** [comment]
@MapoMagpie 🤗

**Comment by MapoMagpie** [comment]
77bea27468cc4ecc9b3fe6ebf173f4a6d4072a70
这里是最新的安装地址: https://github.com/MapoMagpie/eh-view-enhance/raw/master/eh-view-enhance.user.js
