### ISSUE TITLE
[spelling mistakes ] a couple of spelling mistakes 

### ISSUE THREAD

**Issue by darvon123** [MapoMagpie/eh-view-enhance#37]
### [spelling mistakes ] 
"Auto **Flod** Control panels" should be "Auto **Fold** Control panel"
**Don**loadThreads should be DownloadThreads

**Comment by MapoMagpie** [comment]
Thanks, I will fix this.

**Comment by MapoMagpie** [comment]
04b9033f6303808516ff6a28c3ce874b52e24fc6
0301aa5f6bd07bbbf038df21f54383b7b1d65815
These changes will appear in the next releases.
