### ISSUE TITLE
Middle mouse to load tabs in background (rather than focus)

### ISSUE THREAD

**Issue by uwidev** [MapoMagpie/eh-view-enhance#38]
Currently, middle mouse clicking images causes my browser to focus to that newly opened tab. Would it be better to have the tab load in the background so the user can continue looking through the images?

My workflow is to better see an image, and if I like it, I would middle mouse click on it to "bookmark it" to examine it further. I would then examine it after I have a batch and decide whether I wanted to download the original sized image. But because the focus changes automatically, I cannot work efficiently.

I am on Floorp, which is a fork of Firefox. It could be browser settings, as I have not tried on other browsers and it may work differently.

**Comment by MapoMagpie** [comment]
[improve: middle click open in background tab;](https://github.com/MapoMagpie/eh-view-enhance/commit/53d8a9b559b01755c56d879b6d222a8ea22d28f8)

You can install directly from [here](https://github.com/MapoMagpie/eh-view-enhance/raw/master/eh-view-enhance.user.js)
