### ISSUE TITLE
键盘操作没反应？

### ISSUE THREAD

**Issue by GreatSD** [MapoMagpie/eh-view-enhance#39]
想问下为什么在大图浏览状态下键盘左右翻页等所有操作都没反应的？

**Comment by exbranchio** [comment]
I get a test in different browsers. it hasnt exist yet. which broswer(s) you are using? and the version?

**Comment by MapoMagpie** [comment]
你用的什么浏览器，以及哪个站点，还有是否更新到最新版本。

**Comment by GreatSD** [comment]
用的是最新123.0.2420.65 (正式版本) (64 位)的edge浏览器，站点是exhentai.org，插件版本是4.3.13，应该是最新的吧？

**Comment by MapoMagpie** [comment]
同样的环境，不能复现，你可以检查下你有安装什么会影响到快捷键的拓展或脚本吗，比如vimium。或者有什么拓展或脚本影响到页面元素的聚焦。
或者在这里安装新的版本看看问题是否依旧存在: https://github.com/MapoMagpie/eh-view-enhance/raw/select-chapters/eh-view-enhance.user.js
