### ISSUE TITLE
[enhancement]: onion website support

### ISSUE THREAD

**Issue by exbranchio** [MapoMagpie/eh-view-enhance#40]
Since E-hentai has a onion website [exhentai onion](http://exhentai55ld2wyap5juskbm67czulomrouspdacjamjeloj7ugjbsad.onion), we can access exhentai through [Tor Browser](https://www.torproject.org/).
Apart from the link, it's totally the same to exhentai.org, so it should be not very hard to add this site in.

**Comment by MapoMagpie** [comment]
I will add it to the plan

**Comment by MapoMagpie** [comment]
Thanks for the PR, but `eh-view-enhance.user.js` is a build product of vite. 
I do the same commit and these changes will be merged into the next version.
04e6ac3dcafaadb9fc06333b265de804f6efe9d7
