### ISSUE TITLE
Unable to function properly on MacOS and Safari browser.

### ISSUE THREAD

**Issue by DouiKo** [MapoMagpie/eh-view-enhance#43]
**Describe the bug**
Unable to function when using UserScripts as a script loader, specifically manifested by the lack of a browsing mode icon in the bottom left corner.

Can function properly when using Stay as a script loader. Since the Userscripts plugin is free and open source, this is the choice of most macOS users. Hope to add support for Userscripts.

I have not used JavaScripts before. If you could point out where the issue lies in the code, I hope I can assist you in debugging.

**Browser And Version**
Browser: Safari 17.0 (19616.1.27.211.1)
Script loader application: UserScripts

**Log**
<img width="1131" alt="image" src="https://github.com/MapoMagpie/eh-view-enhance/assets/36651688/c568967a-e4fa-4525-8aa5-88e1d4406ddb">

**Comment by MapoMagpie** [comment]
It looks like `GM_getValue` is undefined, but I see that `UserScripts` already implements these APIs: https://github.com/quoid/userscripts?tab=readme-ov-file#api
I will try to test this issue.
Now, you can try reinstall from here: https://github.com/MapoMagpie/eh-view-enhance/raw/gm_api/eh-view-enhance.user.js

**Comment by DouiKo** [comment]
I tested https://github.com/MapoMagpie/eh-view-enhance/raw/gm_api/eh-view-enhance.user.js, but it seems to still not work. The current situation is as follows:

After searching just now, I found a workaround and hope this PR can offer some help. Thank you for your work.

**Comment by MapoMagpie** [comment]
fb08fbe6050b48a8da4f91c3c5a19c8316456bc3
