### ISSUE TITLE
Multiple page Hitomi.la closes viewer

### ISSUE THREAD

**Issue by lnp5131** [MapoMagpie/eh-view-enhance#45]
Using left or right to navigate in Hitomi.la for large enough galleries to have multiple pages would close the viewer on left/right. Opening the viewer again would show no pages if on page 2 or higher. 
![image](https://github.com/MapoMagpie/eh-view-enhance/assets/46536684/00e85601-e6b2-47ac-bb60-cee5c32aa870)
The script responsible is likely https://ltn.hitomi.la/gallery.js

**Comment by MapoMagpie** [comment]
[fix: keyboard event propagation;](https://github.com/MapoMagpie/eh-view-enhance/commit/756ee21a768a76cd4d46671542a78e34ef23a9bf)

**Comment by lnp5131** [comment]
The issue returned ever since the rename to Comic Looms. The same script is responsible. 

```
$(document).keydown(function(e) {
        var evtobj = window.event ? event : e;
        if (evtobj.altKey || evtobj.ctrlKey || evtobj.shiftKey || evtobj.metaKey) return;
        
        var current_page_el = $(".currentPage");
        
        switch (e.which) {
                case 37: //left
                        if (current_page_el.prev().children().length) {
                                window.location.hash = current_page_el.prev().children()[0].hash;
                        }
                        break;
                case 39: //right
                        if (current_page_el.next().children().length) {
                                window.location.hash = current_page_el.next().children()[0].hash;
                        }
                        break;
                default: return;
        }
        
        e.preventDefault();
});
```

**Comment by lnp5131** [comment]
@MapoMagpie Keydown event listener was replaced by a keyup event listener in the rewrite. Reverting back to keydown fixes this issue.
