### ISSUE TITLE
Add auto-open eh-view-enhance on gallery open option

### ISSUE THREAD

**Issue by ripdog** [MapoMagpie/eh-view-enhance#48]
Hi again~

Currently, eh-view-enhance only opens when the book icon is clicked in the bottom left. However, I never want to use the default viewer, so it would be fantastic if I could enable an option to always open eh-view-enhance automatically when I open a gallery page. 

Thanks for your hard work!

**Comment by ripdog** [comment]
Hmm, thinking about e-h server load, it might be a good idea to not load full images until the tab is in focus. I like to open all the galleries I'm interested in at once, then leave the tab open for weeks until I actually read it.

**Comment by MapoMagpie** [comment]
Added, Now, You can install directly from [here](https://github.com/MapoMagpie/eh-view-enhance/raw/master/eh-view-enhance.user.js)
The new version release on Greasyfork will be delayed for a few days.

The default setting of `Auto Open` is false.
And the new option `Keep Loading` is used to keep automatic loading even when the window loses focus, with a default setting of true

**Comment by ripdog** [comment]
Thank you very much! I can confirm the new functions work well. This is a huge improvement to the usability of e-h! 👍
