### ISSUE TITLE
Viewer Shows a Grey Outline

### ISSUE THREAD

**Issue by EyoNella** [MapoMagpie/eh-view-enhance#50]
After turning off and then turning on again, the viewer caused a problem where there is now a grey outline blocking the pictures from showing and when going into big mode it only disappears when the mouse isn't hovering over the area. Hard to describe but there is also the mini controls appear at the top now and the configuration is behind the outline so I can't access it further.

![Screenshot 2024-05-03 185826](https://github.com/MapoMagpie/eh-view-enhance/assets/168876295/2b397bab-69c6-4731-a7ee-f2af98e616d8)

**Comment by MapoMagpie** [comment]
I cannot reproduce this issue.
May be affected by other extensions or scripts.
Can you disable other extensions or scripts and try again?
Or just reinstall eh-view-enhance.

**Comment by EyoNella** [comment]
Yes reinstalling worked thank you
