### ISSUE TITLE
脚本的图标未显示

### ISSUE THREAD

**Issue by QiQi777iii** [MapoMagpie/eh-view-enhance#51]
![image](https://github.com/MapoMagpie/eh-view-enhance/assets/141505720/4799a188-6132-4369-a655-c2725d2003a5)
启用了脚本未能找到脚本的图书，脚本为最新版本，已经排除没有因为其他脚本或者拓展导致冲突请问这是否是一个bug

**Comment by MapoMagpie** [comment]
晚上我会装上你图片里的脚本进行测试，查看是否存在冲突问题。
早上在检查另一个问题时已经测试了多个浏览器，包括低内核版本以及chrome的beta版本，一切正常。
你可以通过F12打开浏览器控制台，并将控制台中输出的信息展示出来吗，看看是否有红色或黄色的输出信息。

**Comment by QiQi777iii** [comment]
![image](https://github.com/MapoMagpie/eh-view-enhance/assets/141505720/f795c59a-4193-4403-bb8c-86f1e9a6898f)
这是报错的信息

**Comment by QiQi777iii** [comment]
![image](https://github.com/MapoMagpie/eh-view-enhance/assets/141505720/8eeca71f-a43e-4bd5-b241-eb72b46a9c9c)
这是报错的信息

**Comment by QiQi777iii** [comment]
![image](https://github.com/MapoMagpie/eh-view-enhance/assets/141505720/0e2a1a5f-de41-4c52-8bc6-07b5fbf3c7aa)
这个是脚本报错的信息

**Comment by QiQi777iii** [comment]
![image](https://github.com/MapoMagpie/eh-view-enhance/assets/141505720/2e60afe5-cfaa-4c6c-a642-695b184e6a36)
这个是脚本报错的信息

**Comment by QiQi777iii** [comment]
这是GPT给的解释

这段代码中的错误信息是指在执行一个名为 `E-HENTAI-VIEW-ENHANCE.user.js` 的用户脚本时遇到了一个问题。具体来说，这个错误消息指出在脚本的第 6720 行尝试调用一个名为 `saveAs` 的函数时，发现该函数未被定义。

错误信息解释如下：

- `Uncaught (in promise) ReferenceError: saveAs is not defined`：这意味着在执行异步操作（promise）期间，尝试访问一个名为 `saveAs` 的变量或函数，但是这个变量或函数没有在当前作用域或全局作用域下定义。`ReferenceError` 是JavaScript中表示引用错误的错误类型之一，出现这种错误通常是因为尝试访问一个未声明的变量。

- `at Proxy.<anonymous>` 和后续的几个调用栈信息提供了错误发生的上下文，包含了出错的文件名（`E-HENTAI-VIEW-ENHANCE.user.js`），以及一个唯一的标识符（`id=f9d21232-2fb9-4f1b-b895-507982766912`），还有出错的行数（6720行）。

针对这个错误，可能的解决方法包括：

1. **检查 `saveAs` 函数是否已经定义**：确保你的脚本中或者你的环境中包含了 `saveAs` 函数的定义。`saveAs` 函数通常用于触发浏览器下载操作，它可能是一个第三方库提供的功能（如FileSaver.js）。

2. **引入缺失的库**：如果 `saveAs` 函数来源于某个库（如FileSaver.js），请确保这个库已经被正确引入到你的项目中。

3. **检查作用域**：如果 `saveAs` 函数是由你自己定义的，确认它的定义位置是否能被当前的执行环境所访问。

4. **异步代码处理**：由于错误发生在一个promise中，如果 `saveAs` 的定义是异步加载的，需要确保在尝试调用 `saveAs` 之前，其定义已经加载完成。

5. **调试和日志记录**：在尝试调用 `saveAs` 函数之前，可以添加日志记录来确认其是否已经定义。这可以通过简单地在调用前打印出 `saveAs` 的值来实现（例如，使用 `console.log(saveAs)`）。

解决这类问题通常需要详细检查代码，确认所有需要的依赖都已正确加载，并确保没有作用域等基本的JavaScript错误。

**Comment by MapoMagpie** [comment]
看起来像是引用的三个js库因为网络原因没有加载出来，https://cdn.jsdelivr.net 这个站点你访问不了了，代理开全局或为这个站点添加代理规则试试

**Comment by QiQi777iii** [comment]
好的解决完了，机场的原因自动屏蔽证书无效的网站了，麻烦你了
