### ISSUE TITLE
脚本更新后无法使用

### ISSUE THREAD

**Issue by Malcolm-Allen** [MapoMagpie/eh-view-enhance#52]
如题，脚本更新到4.4.11以后无法使用，左下角无按钮

浏览器为最新版本Chrome，版号124.0.6367.119
Tampermonkey版本5.1.1
Tampermonkey beta版本5.2.6195

**Comment by MapoMagpie** [comment]
可能和 #51 一样，因为你无法访问 https://cdn.jsdelivr.net/ 导致所引用的几个js库没有成功引入。
请先试试能否访问  https://cdn.jsdelivr.net/

**Comment by MapoMagpie** [comment]
我已经将之前引用的js库直接打包到脚本里了，请更新到4.4.12尝试。
52a966324b5bd0953596dedce4304cc70b20220a
