### ISSUE TITLE
Big Mode 

### ISSUE THREAD

**Issue by EyoNella** [MapoMagpie/eh-view-enhance#53]
I remember being able to pick a scale and it would stay that way even when going back a page, can we get that back or a toggle feature? It's nuance having to scale it to full screen every time. 

Also when entering big mode it keeps opening a new page of the first picture. I Confirmed it's not the other extensions since I tested it with them turned off.

**Comment by MapoMagpie** [comment]
There are several buttons to control scaling at the bottom of the config panel. 
You can scroll to the bottom of the config panel with the mouse. (I'm thinking about a new layout to improve the experience of browsing pictures.)
Also the default behavior "keep scaling" works fine.


https://gateway.pinata.cloud/ipfs/QmZtdP8fwyE432PUPtqZNhwVAAwG22nmoniodwfqvZwdHL

> Also when entering big mode it keeps opening a new page of the first picture. I Confirmed it's not the other extensions since I tested it with them turned off.

What browser version are you using? I still can't reproduce the problem.

**Comment by EyoNella** [comment]
Google Chrome. The scaling works fine on the same page but when exiting it returns back to default. How do I keep the scaling after I exist the page and click on a different manga? I know that it is right-click plus middle mouse scroll to scale as well as in the config at the bottom.

If even you can't reproduce the new page problem then I guess it's really a problem on my end. I'll just click instead of using the keyboard from now on.

**Comment by MapoMagpie** [comment]
16c3a4ecebbc724379a10e227198b5c719ab81e3

Fixed the issue where the image scaling configuration was incorrectly reset every time the page was entered.

**Comment by EyoNella** [comment]
Updated to new version and all good now, thanks

**Comment by MapoMagpie** [comment]
I reproduced the second issue, and indeed, when enter bigImageMode via keyboard shortcuts, it does open a new tab. 
Sorry, I'm not frequently using keyboard shortcuts.

**Comment by EyoNella** [comment]
Ahh alright, I do hear a lot of people using firefox so no one's fault. Good to know it wasn't a problem with just me but the use of different browser.
