### ISSUE TITLE
Question: about  download option

### ISSUE THREAD

**Issue by reisgemx** [MapoMagpie/eh-view-enhance#58]
Hello, first off I would like to say thank you for your excellent job!! I have no problem, but a question. When I use the download option, it always uses the JP name of the gallery on E-H. / Ex-H even if it was a gallery of a translated version with an English name. I tried looking at configurations but couldn't find anything about this. Is there a way I could make the extension priorize an English name or Romaji name first, then JP kanji/hiragana name?

![image](https://github.com/MapoMagpie/eh-view-enhance/assets/86016575/14189115-05b5-4a7c-a6cd-08b18b181012)

**Comment by MapoMagpie** [comment]
Added, There is a new option of `EHentai Prefer Title` in config panel. it's default value is `Japanese`.

**Comment by reisgemx** [comment]
> Added, There is a new option of `EHentai Prefer Title` in config panel. it's default value is `Japanese`.

Worked perfectly. Thank you!!
