### ISSUE TITLE
Hentai Nexus Image Bug

### ISSUE THREAD

**Issue by ghost** [MapoMagpie/eh-view-enhance#62]
Script worked great on HentaiNexus for a couple of days, but suddenly a bug appeared.
Seem to have started occurring when they implemented downloads, though not sure if related to bug.

**Describe the bug**
When attempting to use the user-script, images are displayed with error code `Error: fetch bit image url error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`.
If attempting to use regardless, images appear at a low resolution.

**Browser And Version**
Firefox 126.0.1-1

**Log**
Error code when opening a book's profile page: `Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://{redacted}/userscripts/E-HENTAI-VIEW-ENHANCE.user.js?id={redacted}
Source Map URL: hammer.min.js.map`.
Error code which occurs for each image when attempting to use script: `EHVP:fetch image error, try times: 1, error: Error: fetch big image url error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`.

**Screenshots**
https://i.ibb.co/vwpV3HX/screen.png

**Comment by MapoMagpie** [comment]
Looks like they updated the decryption function `reader.min.js?r=22`, I'll fix this.

**Comment by MapoMagpie** [comment]
[fix: hentainexus decryption](https://github.com/MapoMagpie/eh-view-enhance/commit/0d99216c4c4406b309b9b795c881bdbb20d03c96) https://github.com/MapoMagpie/eh-view-enhance/issues/62[;](https://github.com/MapoMagpie/eh-view-enhance/commit/0d99216c4c4406b309b9b795c881bdbb20d03c96)
