### ISSUE TITLE
建议：推特能增加直接下载功能么？

### ISSUE THREAD

**Issue by casinohoi** [MapoMagpie/eh-view-enhance#63]
**Describe the bug**
建议：推特能增加直接下载功能么？

**Browser And Version**
Which Browser Do You Use? And Browser Version
firefox 最新的

**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

**Screenshots**
如果可以，请提供安全的图片

**Comment by MapoMagpie** [comment]
不是已经下载功能了吗，可以详细描述下你的需求吗？
是进入推主的主页后自动开始下载？
还是说在脚本的入口按钮那里增加一个下载的按钮，而不用打开阅读界面？
还是什么其他的效果，请详细说明。

**Comment by casinohoi** [comment]
> 不是已经下载功能了吗，可以详细描述下你的需求吗？ 是进入推主的主页后自动开始下载？ 还是说在脚本的入口按钮那里增加一个下载的按钮，而不用打开阅读界面？ 还是什么其他的效果，请详细说明。

简单来说，是推特总是下载失败啊，我在eh下载是没问题的，但是在x上就是下再失败。其实，我也不是要打包某人全部的图片（和eh的逻辑不一样），我想要一部分图片的下载

**Comment by MapoMagpie** [comment]
虽然没有直接的`挑选图片`功能，但现在是可以间接做到的，这点在脚本的帮助页里有写到。
或者提供下关于`挑选图片`这个功能的建议，希望它是怎样的交互方式之类的？
