### ISSUE TITLE
建议：在范围选择页面增加一些快捷按钮

### ISSUE THREAD

**Issue by kakuri2020** [MapoMagpie/eh-view-enhance#65]
**Describe the bug**

### Basic

按钮1：从当前页开始（当前大图）
按钮2：从当前页结束（当前大图）

按钮1和按钮2共同维护一个range，range的默认范围为 1-最后一页

在两个按钮都没点击时，不需要实际添加这个range
只点击按钮1时，添加并将range修改为 当前页-最后一页
只点击按钮2时，添加并将range修改为 第一页-当前页

如果两个按钮都点了，就将 range 修改为两者之间

比如说：一个画廊最后几页不需要（例如广告）
可以直接选择最后一个有效页的大图，点击按钮2，再点击下载

可以省去：观察当前大图页的ID，输入 1-ID，点击pick 这几步

### More

甚至可以再直接添加一个按钮3：下载此页及之前的内容，我感觉这个最实用

功能上相当于：点击按钮2，同时开始下载

举例2种常用情况：

1.屏蔽最后几张，只需要找到最后一张有效图，点开对应大图，然后点击按钮3
```
例如总共30页，下载 1 - 26页，
只需要点击26页，然后点击按钮3
```

2.下载画廊种的某些页数（连续）：选中第一张有效图，点击按钮1，然后选中最后一张有效图，点击按钮3
```
例如总共400页，下载 32-51页，
需要点击32页，点击按钮1，再点击51页，然后点击按钮3
```

**Browser And Version**
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？

**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

**Screenshots**
如果可以，请提供安全的图片

**Comment by MapoMagpie** [comment]
更新了，不过面板自动折叠会让操作繁琐，现在可以在缩略图界面 ctrl+鼠标左键某张图片后，会选择该图片，然后ctrl+shift+鼠标左键另一张图片后，会直接选择两图之间的范围。

**Comment by kakuri2020** [comment]
可不可以，使用ctrl + shift + 左键的时候，如果没有通过  ctrl + 左键选择过开头，则默认以第1张作为开头

也就是自动选择  1 - 当前张

**Comment by kakuri2020** [comment]
work good for me 👍
