### ISSUE TITLE
Suggestion: Auto Page Speed Set to Duration When Autoplaying Videos

### ISSUE THREAD

**Issue by matterdog** [MapoMagpie/eh-view-enhance#66]
When auto playing videos it would make sense to have an option to play the entire video before proceeding. 

Currently, depending on your set auto paging speed and the duration of a video, a video will either be cut off or looped several times. If it is possible to change the interval to the currently playing video I believe the experience would be much better.

**Comment by MapoMagpie** [comment]
added
