### ISSUE TITLE
问题：下载保存压缩包的问题

### ISSUE THREAD

**Issue by onlye2099** [MapoMagpie/eh-view-enhance#67]
分卷压缩容易报错，能直接打包成一个压缩包吗？

有一点反直觉，第一眼看过去能解压的文件解压了，但是会报错。
![image](https://github.com/MapoMagpie/eh-view-enhance/assets/89190608/70c193b4-1b3b-4f38-8de5-b95480ac63ad)
![image](https://github.com/MapoMagpie/eh-view-enhance/assets/89190608/80ae4c27-e756-4f44-99ca-ca8c8e4bc846)

摸了半天没搞懂，然后解压Z01文件倒是解压出来了没绷住。

用2345好压解压会出现错误，只能解压一部分文件。
![image](https://github.com/MapoMagpie/eh-view-enhance/assets/89190608/794da4b4-da7e-40b6-bfde-06c906981171)
用Bandizip会说损坏。
![image](https://github.com/MapoMagpie/eh-view-enhance/assets/89190608/b1c59725-c895-416a-a358-c41edca14725)
用7-Zip提取则不会报错，并且全部内容都能解压出来。
![image](https://github.com/MapoMagpie/eh-view-enhance/assets/89190608/d92d8b47-bcb4-4f39-9df5-604a13598634)

**Comment by MapoMagpie** [comment]
我记得之前添加分卷压缩功能的时候，是有这个问题。
不过更新了bandizip后就可以了，试试更新bandizip

**Comment by onlye2099** [comment]
嗯，建议还是说一下这个问题，不然确实有点懵逼

**Comment by MapoMagpie** [comment]
分卷压缩是因为浏览器对单个对象的大小有限制，chrome限制为内存的1/5，firefox 2G。超过限制无法打包下载。
我会在帮助页加一个说明，提醒解压软件更新的问题。
