### ISSUE TITLE
Blacklisted images on some sites still show.

### ISSUE THREAD

**Issue by HahaLongB0y** [MapoMagpie/eh-view-enhance#70]
This script shows blacklisted images on some sites, is there anyway you can fix this issue?

**Comment by MapoMagpie** [comment]
which site?

**Comment by HahaLongB0y** [comment]
Danbooru

**Comment by MapoMagpie** [comment]
fixed
you can install directly from here: https://github.com/MapoMagpie/eh-view-enhance/raw/master/eh-view-enhance.user.js

**Comment by HahaLongB0y** [comment]
legend!
