### ISSUE TITLE
Hentai Nexus Image Bug (v2)

### ISSUE THREAD

**Issue by ghost** [MapoMagpie/eh-view-enhance#71]
**Describe the bug**
When attempting to use the user-script, images are displayed with error code `Error: fetch bit image url error: Error: cannot find reader data`.
If attempting to use regardless, images appear at a low resolution.

**Browser And Version**
 Firefox 126.0.1-1

**Log**
`EHVP:fetch image error, try times: 1, error: Error: fetch big image url error: Error: cannot find reader data`

**Screenshots**
https://i.ibb.co/GvSs4hJ/screen.png

**Comment by MapoMagpie** [comment]
fixed, 
update directly from here :https://github.com/MapoMagpie/eh-view-enhance/raw/master/eh-view-enhance.user.js
