### ISSUE TITLE
只有我有这个bug吗，还是jm的问题，看不了

### ISSUE THREAD

**Issue by neckman112** [MapoMagpie/eh-view-enhance#72]
**Describe the bug**
在此处描述问题
jm基本都看不了

**Browser And Version**
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？
chrome 版本 126.0.6478.127（正式版本） （64 位）

**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。
userscript.html?name…bd-1bebf1f3a09f:340 2024/7/16 02:34:38 EHVP:fetch image error, try times: 1, error: 
Error: expect image data, fetched wrong type: text/html; charset=utf-8
    at Object.onload (userscript.html?name…1bebf1f3a09f:621:22)
    at wt (<anonymous>:9:89)
    at <anonymous>:36:335
    at wt (<anonymous>:9:89)
    at r (<anonymous>:24:484)
    at <anonymous>:25:112
    at <anonymous>:76:491
    at v (<anonymous>:77:15)

**Screenshots**
如果可以，请提供安全的图片

![image](https://github.com/user-attachments/assets/e793fdaf-52ec-4075-960b-3b4a6dd7bb03)
![1](https://github.com/user-attachments/assets/5ed13d4b-e645-4909-9a07-244e62dd3552)

**Comment by MapoMagpie** [comment]
正常情况下没有复现，浏览的中途将代理节点切换到日本后复现了，可能是你网络的原因导致的。
你可以在某张缩略图上通过鼠标中键打开图片的原始地址，看看是否被block了还是触发机器人验证了。
如果你有使用clash，节点组是负载均衡的话，是有可能出现18comic.xxx的主站可以访问，但是图片服务器(cdn-mps1.18comic.xxx)无法访问的情况的

总之请在缩略图上通过鼠标中键打开图片的原始地址查看访问情况。

**Comment by neckman112** [comment]
哦对不起，忘记给你截一个原始地址的图片了，这个图片很奇怪。
![image](https://github.com/user-attachments/assets/cda0ead2-2658-4917-9ebf-ca6fbb2f8fec)
然后目前的话，在所有支持的网站里面，就只有jm是这样的

**Comment by neckman112** [comment]
代理用的是浏览器的一个插件，我也试过v2ray，效果是一样的

**Comment by MapoMagpie** [comment]
无法在chrome上复现。

图片的原始地址能打开，说明网络没问题，至于图片很奇怪，那是因为禁漫为了防盗对原始图片做了乱序切割。

姑且从这里更新试试: https://github.com/MapoMagpie/eh-view-enhance/raw/master/eh-view-enhance.user.js

如果还是这样，麻烦试试其他浏览器如edge是否有同样的问题。

**Comment by neckman112** [comment]
找到原因了卧槽，是我一个浏览器插件的原因，可恶，浪费大哥时间了。一个浏览器代理插件，叫无忧行，你可以复现试试，但是为啥呢，是这个代理流量不稳吗
