### ISSUE TITLE
Add support for Koharu

### ISSUE THREAD

**Issue by ty5e3a45** [MapoMagpie/eh-view-enhance#73]
Possible to add support for Koharu dot to?

**Comment by MapoMagpie** [comment]
added: [support: koharu.to](https://github.com/MapoMagpie/eh-view-enhance/commit/029c8b8f98eae167fc3c3e3e69a3534e743dc0c1)

**Comment by MapoMagpie** [comment]
fixed: [include separate domain of kaharu.to](https://github.com/MapoMagpie/eh-view-enhance/commit/7a66e1e33589e0b4ed6f80e3c892d5a2314db074)
