### ISSUE TITLE
请求添加让用户自己添加网站的功能

### ISSUE THREAD

**Issue by Tekashi-gif** [MapoMagpie/eh-view-enhance#74]
**Describe the bug**
比如wnacg这个网站的国内镜像经常更新，更新后脚本就不支持进入阅读模式了，可不可以添加一个设置入口让用户可以添加新的镜像网址？

**Browser And Version**
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？
火狐浏览器国际版 128.0(64位）
**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

**Screenshots**
如果可以，请提供安全的图片

**Comment by MapoMagpie** [comment]
添加了站点配置功能，可以配置某个站点的工作地址，只是需要一些正则知识。

不过我已经更新了wnacg镜像站的地址，应该不用配置了。

如果镜像站域名从wn00.cc变成其他字母开头的，可以在站点配置里添加工作地址，类似这样: `wn\d{2}.cc/photos-index`

你可以在这里直接重新安装: https://github.com/MapoMagpie/eh-view-enhance/raw/master/eh-view-enhance.user.js

**Comment by MapoMagpie** [comment]
设置脚本的`@match`为`*://*/*` 在greasyfork上会被标记为作用于所有网站，然后就不能通过站点查找到这个脚本，导致没人下载了。
所以我取消了 `@match *://*/*` ,也就是“自行添加网站“这个功能不能用了。

替代的办法是自行在脚本管理器中编辑这个脚本的代码，在类似`@match https://xxx.com/*`的代码下面增加对应的地址，比如增加`// @match https://*.wn03.cc/*`，或者向我反馈新地址再进行更新。

[chore: specify the site of @match explicitly; ](https://github.com/MapoMagpie/eh-view-enhance/commit/be3da71e973bf99ae2a14597d76429eb1ba245b6)

**Comment by Tekashi-gif** [comment]
谢谢大佬🫡🫡

**Comment by Carolove7** [comment]
> 设置脚本的`@match`为`*://*/*` 在greasyfork上会被标记为作用于所有网站，然后就不能通过站点查找到这个脚本，导致没人下载了。 所以我取消了 `@match *://*/*` ,也就是“自行添加网站“这个功能不能用了。
> 
> 替代的办法是自行在脚本管理器中编辑这个脚本的代码，在类似`@match https://xxx.com/*`的代码下面增加对应的地址，比如增加`// @match https://*.wn03.cc/*`，或者向我反馈新地址再进行更新。
> 
> [chore: specify the site of @match explicitly; ](https://github.com/MapoMagpie/eh-view-enhance/commit/be3da71e973bf99ae2a14597d76429eb1ba245b6)

最新版我加入镜像站后油猴显示正在运行，但是并没有出现按钮
