### ISSUE TITLE
添加暂停自动播放的快捷键

### ISSUE THREAD

**Issue by Khoroamu** [MapoMagpie/eh-view-enhance#78]
**Describe the bug**
希望添加暂停自动播放的快捷键

**Browser And Version**
版本 127.0.6533.89（正式版本） （64 位）

**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

**Screenshots**
如果可以，请提供安全的图片

**Comment by MapoMagpie** [comment]
已添加
