### ISSUE TITLE
Can't drag images after recent update

### ISSUE THREAD

**Issue by waeifu** [MapoMagpie/eh-view-enhance#81]
I often use this feature to download images. Now it doesn't work.
**Browser And Version**
Edge

**Comment by MapoMagpie** [comment]
A new Magnifier feature was recently added, which prevents image dragging. 
I have now added a "Magnifier" option, and when it is Disabled(Default is Disabled), images can be dragged again.

You can install directly from here: https://github.com/MapoMagpie/eh-view-enhance/raw/master/eh-view-enhance.user.js
