### ISSUE TITLE
[Enhancement] Go from website's default thumbnail viewer directly to big image viewer

### ISSUE THREAD

**Issue by 0neW0rld** [MapoMagpie/eh-view-enhance#82]
Hi, is it possible to add the option to go from a website's default thumbnail viewer directly to this script's big image viewer and vice versa? I'm requesting this is because I'd like to interact with a site's original thumbnail viewer where I can see gallery info/tags, add a gallery to my favorites, etc. without having to toggle this script's custom thumbnail viewer on and off. Thanks.

**Comment by MapoMagpie** [comment]
Sorry, I can't fully understand the design you're expecting. Could you describe the specific operation in more detail? 
BTW, I’ve added a new option called "Auto Big", which allows you to open the big image viewer directly after clicking the script's entry.  If you fold it and open it again, the big image view will still be retained.

**Comment by MapoMagpie** [comment]
I just pushed the update to Greasy Fork, so you can try updating it now.
Or install directly from: https://github.com/MapoMagpie/eh-view-enhance/raw/master/eh-view-enhance.user.js

> 2.Click on a thumbnail

I'm quite resistant to adding this function, as I don't want to modify elements on the original page. Additionally, you won't be able to click on thumbnails on the second page of the gallery. If you switch to the second page, the page will refresh, and the script will reload the entire gallery.
