### ISSUE TITLE
unable to download images on e621.net

### ISSUE THREAD

**Issue by Byzz2077** [MapoMagpie/eh-view-enhance#83]
Unable to download images on e621.net
在此处描述问题

Firefox V.129
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？

`Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'self' https://ads.dragonfru.it/ https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.recaptcha.net/ 'nonce-F7cX5sUw5Xuo8gL1HEEK3Q=='” [content_script.js:6:22](moz-extension://3dcd09a7-17dc-4683-a1cd-1f51ac1a0d6f/content_script.js)

Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'nonce-968ddc8fa5377dabf1b1cf3eff805071' 'self' https://ads.dragonfru.it/ https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.recaptcha.net/ 'nonce-F7cX5sUw5Xuo8gL1HEEK3Q=='” [content_script.js:6:22](moz-extension://3dcd09a7-17dc-4683-a1cd-1f51ac1a0d6f/content_script.js)

Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'self' https://ads.dragonfru.it/ https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.recaptcha.net/ 'nonce-F7cX5sUw5Xuo8gL1HEEK3Q=='” 2 [content.js:60:437](moz-extension://99ffbee2-b8a1-4498-b86d-e9bc1af03ffd/content.js)

Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'self' https://ads.dragonfru.it/ https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.recaptcha.net/ 'nonce-F7cX5sUw5Xuo8gL1HEEK3Q=='” [index.js:7410:27](moz-extension://a814b26d-4113-4bf3-91f2-2fa6dcea1638/inject/index.js)

Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'nonce-968ddc8fa5377dabf1b1cf3eff805071' 'self' https://ads.dragonfru.it/ https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.recaptcha.net/ 'nonce-F7cX5sUw5Xuo8gL1HEEK3Q=='”

Error: Permission denied to access property "autoAllocateChunkSize"`

Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

![Screenshot 2024-08-19 120011](https://github.com/user-attachments/assets/ffdbca19-f11b-4f11-8097-b9cb9d0ecff1)

**Comment by MapoMagpie** [comment]
Have you successfully downloaded it before?

I am unable to reproduce this issue, including in Firefox and Chrome. 
One possible cause could be that Firefox failed to redirect to e621.net. You can try accessing e621.net directly or use Chrome to check if the issue still persists.

**Comment by Byzz2077** [comment]
apologies, it turns out there is an incompatibility with the Firefox [swift selection search ](https://addons.mozilla.org/en-US/firefox/addon/swift-selection-search/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) extension.
Disabling it fixed the issue, I thought I already tested it with all extensions disabled but apparently I missed that one, sorry again
