### ISSUE TITLE
[改进] pixiv 上的漫画可否只加载当前章节的内容

### ISSUE THREAD

**Issue by kakuri2020** [MapoMagpie/eh-view-enhance#84]
**Describe the bug**
例如：
https://www.pixiv.net/users/167786/manga 里面的
https://www.pixiv.net/artworks/115646070
打开脚本会加载467张图，如果可以只加载所属的74张会好点

还有就是下载的文件名也可以优化一下

**Browser And Version**
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？

**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

**Screenshots**
如果可以，请提供安全的图片

**Comment by MapoMagpie** [comment]
添加了新的选项，具体说明请在配置面板中查看。
下载的文件名优化什么？

**Comment by kakuri2020** [comment]
就是目前下载的文件名是 PIXIV_167786_w306_p609 类似这样的
可否通过 title 或者
![image](https://github.com/user-attachments/assets/f76235f4-d6fc-4f76-a824-0ed7402b210e)
这样的标签来获取下载后文件的名字 “今日の美沙子さん 2023-C”

当然，可以仅在你添加的新选项打开时生效

**Comment by kakuri2020** [comment]
感谢，最新版本4.7.7 工作正常
