### ISSUE TITLE
Add support for arca.live

### ISSUE THREAD

**Issue by tasoo-oos** [MapoMagpie/eh-view-enhance#85]
[Arca.live](https://arca.live/) is an internet forum.

Like [this post](https://arca.live/b/lovelove/114314176?p=2), there are posts that consist of multiple images, but there isn't a useful image viewer to browse through them.

Could you please add support for this site?

**Comment by tasoo-oos** [comment]
I saw you comitted for my request! 
I tested v4.7.6 on chrome and other chromium-based browser called naver whale and it works flawlessly!
Thank you for the support of this site.

**Comment by MapoMagpie** [comment]
At certain times, the script couldn't retrieve images, so I fixed this issue.
Since I'm not very familiar with this forum, there might still be some minor problems.

**Comment by tasoo-oos** [comment]
I'll try to fix some if there are some and make pull request about it.
Thank you!
