### ISSUE TITLE
添加网站失败

### ISSUE THREAD

**Issue by yukinochenshangpeng** [MapoMagpie/eh-view-enhance#92]
- 18comic换了镜像网站https://18comic-gura.me/，自行添加网站失败
- 
![Snipaste_2024-09-07_19-35-16](https://github.com/user-attachments/assets/314342ff-8428-41b2-9b55-d5df668e4a22)

- Chrome 已是最新版本

版本 128.0.6613.120（正式版本） 

![Snipaste_2024-09-07_19-40-41](https://github.com/user-attachments/assets/27c27b12-e776-4a7f-b1aa-b3f813311bc7) f12截图

- 无论如何先感谢大佬！做的体验太好了，没有缩略图回不去了，直到失去才懂得珍惜。自己弄了一个多小时，还学会了点JavaScript
-

**Comment by MapoMagpie** [comment]
正确添加是这样的：
```
// @match https://18comic-gura.me/*
或者直接匹配所有网站
// @match *://*/*
```
然后配置面板 > 站点配置 > 禁漫 > 添加规则:
```
18comic-gura.me\/album\/\d+
```
不过我刚刚进行了更新，支持了这个新的镜像站。
之所以不直接匹配所有网站是因为添加 `// @match *://*/*`之后，greasyfork不能再通过站点搜索搜索到这个脚本了。

总之你现在不用改了，可以直接在这里更新: https://github.com/MapoMagpie/eh-view-enhance/raw/master/eh-view-enhance.user.js

**Comment by yukinochenshangpeng** [comment]
谢谢！
