### ISSUE TITLE
提供默认下载的选项 +下载快捷键

### ISSUE THREAD

**Issue by AvoidantPerDis** [MapoMagpie/eh-view-enhance#93]
**Describe the bug**
我是仓鼠党，喜欢屯本地，每次下载都要手动点还是比较麻烦

**Browser And Version**
Which Browser Do You Use? And Browser Version
edge最新

**Comment by MapoMagpie** [comment]
加了一个快捷键`Ctrl+Alt+d`，直接开始下载。暂时只作用于未打开脚本阅读界面之前，以及不支持18comic的多章节。
先凑合用着。

**Comment by AvoidantPerDis** [comment]
感谢
