### ISSUE TITLE
脚本无法使用

### ISSUE THREAD

**Issue by whisper649** [MapoMagpie/eh-view-enhance#95]
左下角无按钮

chrome 版本 128.0.6613.138（正式版本） （64 位）
Tampermonkey版本5.2.3
脚本4.8.4

控制台提示：
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.

![屏幕截图 2024-09-12 023634](https://github.com/user-attachments/assets/b1389874-d94a-4cbf-938e-872683874dec)

**Comment by MapoMagpie** [comment]
哪个站点

**Comment by whisper649** [comment]
貌似哪个站点都不行

**Comment by MapoMagpie** [comment]
明天再看

**Comment by MapoMagpie** [comment]
Tampermonkey有提示的，需要在Chrome的拓展管理页面打开“开发者模式”，才能使用Tampermonkey。
https://www.tampermonkey.net/faq.php#Q209

**Comment by MapoMagpie** [comment]
另外你打开的是绅士漫画的镜像站 `qy0.ru`，我并不知道有这个镜像站，所以没有匹配这个地址。
他们官方提供的镜像站是这些，已经支持了。
https://www.wn05.cc
https://www.wn04.cc
https://www.wn03.cc
发布页: https://wnacg.date/

如果你想让脚本在qy0.ru上生效可以参考这里: https://github.com/MapoMagpie/eh-view-enhance/issues/92#issuecomment-2335174533

**Comment by whisper649** [comment]
开发者模式一直是开的。
我也有把这个加在match这里，那几个镜像站点脚本直接不运作。
![屏幕截图 2024-09-12 183404](https://github.com/user-attachments/assets/5daa923c-9fd9-4460-a8bd-20bc71fe6407)

**Comment by MapoMagpie** [comment]
可能是更新脚本后，绅士漫画旧的规则没被覆盖。
那就到其他任意一个支持的站点上打开脚本，点击配置 >站点配置>绅士漫画，点击规则后面的X按钮，会把旧的规则删掉，自动换成新的规则。然后应该就能生效了。

**Comment by whisper649** [comment]
wnacg可以用了，但那些镜像站点还是不行

**Comment by MapoMagpie** [comment]
站点配置里的绅士漫画截图看看，应该还是规则的问题，点删除就好了。

**Comment by whisper649** [comment]
![屏幕截图 2024-09-12 200037](https://github.com/user-attachments/assets/ca240b1d-ddb4-4621-86ed-f4477c809355)

**Comment by MapoMagpie** [comment]
规则在下面，你没截图到，总之删除后会恢复默认规则，如果wnacg能用，wn**.cc的镜像站也一定能用。

**Comment by whisper649** [comment]
![屏幕截图 2024-09-12 211515](https://github.com/user-attachments/assets/3cdcf66f-3d83-4de5-ae9a-6a646c072f3c)

不知道为什么在镜像网站那里油猴显示无运行中的脚本。

**Comment by whisper649** [comment]
![屏幕截图 2024-09-12 213517](https://github.com/user-attachments/assets/dd4fd408-74f5-4bf5-8b1e-2d0d2150063f)
不知道为什么我这里没有

**Comment by MapoMagpie** [comment]
访问地址wn03.cc改成www.wn03.cc，前面加上www.就可以了，看来Tampermonkey更新后不支持 https://*.wn03.cc/* 匹配 https://wn03.cc了，只能匹配到https://www.wn03.cc

**Comment by whisper649** [comment]
可以用了。现在第一种不行了，只能用下面那几种了
![屏幕截图 2024-09-12 222141](https://github.com/user-attachments/assets/0140a625-54db-4bb1-bd81-63a0fa4c308f)
