### ISSUE TITLE
脚本有时可以有时不行

### ISSUE THREAD

**Issue by noobdsx** [MapoMagpie/eh-view-enhance#97]
**Describe the bug**
在此处描述问题
有时可以用，有时不行，返回
Error: timeoutYou can click here retry again,Or press mouse middle button to open origin image url

Error: response status:0, error:undefined, response:undefinedYou can click here retry again,Or press mouse middle button to open origin image url

**Browser And Version**
Which Browser Do You Use? And Browser Version
你使用什么浏览器与版本？
脚本4.9.0
via浏览器 5.8.1
华为emui5.0.2 安卓7
web viewer 119.x
**Log**
Press F12, Open Browser Console. Export or Copy Console Log.
打开浏览器控制台，导出或复制控制台日志，粘贴到此处。

**Screenshots**
如果可以，请提供安全的图片

**Comment by MapoMagpie** [comment]
从错误来看是网络原因，超时了或者图片服务器返回了错误。
不知道你访问的是哪个站点？如果是e[x]hentai，它的图片服务network.hath会被一些安全软件拦截。
检测是否是网络原因，可以直接使用站点原本的方式浏览，如果原本的浏览方式也加载不出来图片，那就是网络的问题。

但也有可能是via浏览器的脚本管理器不支持一些GM_xmlhttprequest的功能导致的。
via浏览器似乎没有violentmonkey和tampermonkey这样“认真可靠”的拓展，你可以在Firefox Android上安装violentmonkey或tampermonkey试试，如果问题依旧，那就只能是网络问题了。

**Comment by MapoMagpie** [comment]
我刚在via浏览器上测试了e-hentai.org，并没有什么问题。所以你应该检查你的网络或者浏览器还装了什么拓展比如安全守护、广告过滤等。

**Comment by noobdsx** [comment]
目前看来跟网络没有关系，不用脚本时候是正常的，用其他设备的via也是正常的，难道是因为webview版本比较低，兼容性不好吗

**Comment by noobdsx** [comment]
目前只在这个设备上发现时得时不得情况

**Comment by MapoMagpie** [comment]
之前有个人在电脑上碰到了E-Hentai上图片部分加载不成功的问题，原因是卡巴斯基拦截了部分图片服务器节点network.hath，
而且奇怪的是卡巴斯基只拦截脚本管理器gm_xmlhttprequest发出的请求，浏览器原生的请求不会被拦截。
#76 

所以看看是否有安全软件在影响，比如你换一个站点如hitomi.la、18comic.vip，这些站点的图片服务器应该不会被什么软件拦截掉。

**Comment by noobdsx** [comment]
试了下上述2个网站，第一个进入阅读模式后，图片为低清晰度图片，并显示undefined报错 第二个没见进入脚本的图标

**Comment by noobdsx** [comment]
测试了nhentai是能正常加载的

**Comment by noobdsx** [comment]
通过网络抓包已找到原因，是证书的问题，导致连接图片服务器时候因为证书不存在断开连接了，导入证书后就正常了

**Comment by MapoMagpie** [comment]
Okey👌
